
system:
  env: ''  # # 	DebugMode = "debug" ReleaseMode = "release"
  addr: 8881
  db-type: 'mysql'
  name: "gin_mall"
  version: v1

# snowflake id config
snowflake:
  start_time: "2020-04-03"
  machine_id: 1

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[gin_mall]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false


mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'gin_mall'
  username: 'root'
  password: 'toor'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: "Info"


jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400
  user_id_name: "userID"
  token_header_name: "Authorization"


redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: "toor"

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

minio:
  bucket_name: "file"
  location: "us-east-1"
  endpoint: "minio.acorn.eu.org"
  accessKeyID: "5LHxOtSinAnngvtA"
  secretAccessKey: "cGT0VEYZ6tH8rwDvkB3BUN6RPC0OkrqZ"
  secure: true


#
#minio:
#  bucket_name: "file"
#  location: "us-east-1"
#  endpoint: "127.0.0.1:9000"
#  accessKeyID: "1BYtcmFq9NY8BsYm"
#  secretAccessKey: "0S9W9oQ8tPwtO94JLbBN38Ulk2fRUb8I"
#  secure: false