basePath: /
host: 127.0.0.1:8888
info:
  contact: {}
  description: This is a sample Server pets
  title: web_app
  version: 0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
